export type AppLocale = 'zh-CN' | 'en-US'

export type MemoryLayer = 'short_term' | 'long_term' | 'fixed' | 'episodic'
export type EntityType = 'person' | 'place' | 'object' | 'event'

const MEMORY_LAYER_LABELS: Record<AppLocale, Record<MemoryLayer, string>> = {
  'zh-CN': {
    short_term: '短期记忆',
    long_term: '旧长期层',
    fixed: '固化记忆',
    episodic: '情景记忆',
  },
  'en-US': {
    short_term: 'Short-Term Memory',
    long_term: 'Legacy Long-Term Layer',
    fixed: 'Fixed Memory',
    episodic: 'Episodic Memory',
  },
}

const ENTITY_TYPE_LABELS: Record<AppLocale, Record<EntityType, string>> = {
  'zh-CN': {
    person: '人物',
    place: '地点',
    object: '物品',
    event: '事件',
  },
  'en-US': {
    person: 'Person',
    place: 'Place',
    object: 'Object',
    event: 'Event',
  },
}

export function getMemoryLayerLabel(layer: MemoryLayer, locale: AppLocale) {
  return MEMORY_LAYER_LABELS[locale][layer]
}

export function getEntityTypeLabel(type: string, locale: AppLocale) {
  if (type === 'person' || type === 'place' || type === 'object' || type === 'event') {
    return ENTITY_TYPE_LABELS[locale][type]
  }
  return ENTITY_TYPE_LABELS[locale].object
}

export function getEntityTypeOptions(locale: AppLocale) {
  return (['person', 'place', 'object', 'event'] as const).map((value) => ({
    value,
    label: ENTITY_TYPE_LABELS[locale][value],
  }))
}

export function getSqliteMemoryCopy(locale: AppLocale) {
  if (locale === 'en-US') {
    return {
      common: {
        none: 'None',
        unknownTime: 'Unknown time',
        loading: 'Loading...',
        previous: 'Previous',
        next: 'Next',
        delete: 'Delete',
        save: 'Save',
        enabled: 'Enabled',
        disabled: 'Disabled',
      },
      errors: {
        load: 'Failed to load sqlite memory',
        delete: 'Failed to delete sqlite memory',
        clear: 'Failed to clear sqlite memory',
        updateLayer: 'Failed to update memory layer',
        edit: 'Failed to save memory edit',
        contextFlush: 'Failed to convert old context',
        sleep: 'Failed to run sleep consolidation',
        settings: 'Failed to save memory settings',
      },
      confirms: {
        deleteSqlite: 'Delete this sqlite memory?',
        clearAll: 'Clear all sqlite memories for this persona? This deletes short-term, legacy long-term, and fixed memories, but keeps chat context, episodic memories, and other personas untouched.',
        deleteEpisodic: 'Delete this episodic memory? Entity nodes and edges will remain.',
        deleteEntity: 'Delete this entity node? Related aliases, edges, and episodic bindings will be removed, while episodic memory text remains.',
        mergeEntity: 'Merge this entity into the target entity? The source will be deleted and aliases, episodic bindings, and edges will migrate.',
        deleteEdge: 'Delete this entity edge?',
      },
      notices: {
        deletedSqlite: 'Deleted this sqlite memory.',
        cleared: (count: number) => `Cleared ${count} sqlite memories for this persona.`,
        layerUpdated: (layer: string) => `Memory layer changed to ${layer}.`,
        savedSqlite: 'Saved STM / fixed memory and rewrote its embedding.',
        savedEpisodic: 'Saved episodic memory and rewrote its summary embedding.',
        createdEpisodic: 'Created episodic memory.',
        deletedEpisodic: 'Deleted episodic memory.',
        createdEntity: 'Created entity node.',
        savedEntity: 'Saved entity node and rewrote entity embedding.',
        deletedEntity: 'Deleted entity node.',
        mergedEntity: 'Merged entity node.',
        savedEdge: 'Saved entity edge.',
        deletedEdge: 'Deleted entity edge.',
        contextFlushStart: 'Converting old context into short-term memories...',
        contextFlushSkipped: (reason: string) => `No old context to convert right now: ${reason}.`,
        contextFlushDone: (created: number, flushed: number) => `Converted active context into ${created} short-term memories and moved out ${flushed} messages.`,
        sleepStart: 'Running sleep consolidation from short-term memory into episodic memory...',
        sleepSkipped: (reason: string) => `No sleep consolidation needed right now: ${reason}.`,
        sleepDone: (episodic: number, entities: number, deleted: number) => `Sleep complete: created ${episodic} episodic memories, added ${entities} entities, and consumed ${deleted} short-term memories.`,
        settingsSaved: 'Memory retrieval settings, models, and Prompt Lab were saved.',
      },
      hero: {
        eyebrow: 'Memory Management',
        title: 'sqlite Memory Console',
        copy: 'This page puts pre-chat retrieval, semantic analysis, and context consolidation controls first, with Prompt Lab below. On wide screens, the memory table stays wide so controls and rows are easier to scan together.',
        count: (total: number) => `${total} total`,
      },
      actions: {
        refresh: 'Refresh',
        flush: 'Convert Context',
        flushing: 'Converting Context...',
        sleep: 'Sleep Now',
        sleeping: 'Sleeping...',
        saveSettings: 'Save Settings',
        clearing: 'Clearing...',
        clearAll: 'Clear All Memories',
      },
      settings: {
        preRetrieval: 'Pre-Chat Retrieval',
        shortTermPill: 'Short-term memory',
        shortTermCopy: 'Adjust how many short-term memories are loaded before the main prompt and how strict matching should be.',
        fixedPill: 'Fixed memory',
        fixedCopy: 'Fixed memory can be stricter or looser than short-term memory so stable facts and recent impressions do not fight each other.',
        semanticLabel: 'Semantic Analysis',
        semanticPill: 'Resolution / tool defaults',
        semanticCopy: 'Controls how much history the semantic analyzer sees, and the default top-k for the episodic memory tool when it is not explicit.',
        noHitOn: 'Show no-hit notice',
        noHitOff: 'Stay quiet on no-hit',
        rhythm: 'Runtime Rhythm',
        contextPill: 'Cache / unload / STM',
        contextCopy: '`context` only lives in the current model context and does not participate in retrieval. These settings control active context size, idle conversion, and how many short-term memories are generated per flush.',
        activeSession: 'Active Session',
        activeContextMessages: 'Active Context Messages',
        totalSessionMessages: 'Total Session Messages',
        activeStartMessage: 'Active Start Message',
        pendingFlushUntil: 'Pending Flush Until',
        lastUserMessage: 'Latest User Message',
        lastContextFlush: 'Latest Context Conversion',
        sleepPill: 'STM / episodic memory',
        sleepCopy: 'Runs a daily sleep pass that consolidates short-term memory into episodic memory and the entity graph. This first version uses fixed local time and fixed day intervals.',
        sleepEnabled: 'Sleep Enabled',
        sleepTime: 'Sleep Time',
        sleepIntervalDays: 'Sleep Interval Days',
        lastSleep: 'Latest Sleep',
        modelLabel: 'Model Settings',
        modelPill: 'Retrieval / tool / consolidation',
        modelCopy: 'Memory model settings live here. Empty values inherit the persona main model; embedding provider is explicit and the embedding model falls back to the system default.',
        memoryModelPlaceholder: 'e.g. qwen/qwen-2.5-7b-instruct',
        embeddingModelPlaceholder: 'e.g. qwen/qwen3-embedding-8b',
      },
      graph: {
        label: 'Entity Graph',
        nodesUnit: 'nodes',
        edgesUnit: 'edges',
        copy: 'Entity nodes, aliases, and untyped weighted edges are maintained by background merge/consolidation. This view queries and paginates them instead of rendering the whole graph at once.',
        searchLabel: 'Search Nodes and Edges',
        searchPlaceholder: 'Search entity names, aliases, or edge endpoints',
        searchState: (query: string) => query ? `Graph search: ${query}` : 'Showing recent nodes and highest-weight edges',
        addEntity: 'Add Entity Node',
        name: 'Name',
        namePlaceholder: 'e.g. StarCraft II',
        type: 'Type',
        confidence: 'Confidence',
        aliases: 'Aliases (comma or newline separated)',
        aliasesPlaceholder: 'SC2\nStarCraft 2',
        description: 'Description',
        descriptionPlaceholder: 'What this node means in the personal memory graph',
        createEntity: 'Add Entity',
        nodesTitle: 'Entity Nodes',
        page: (page: number, pages: number) => `Page ${page} / ${pages}`,
        emptyNodes: 'No entity nodes yet.',
        emptyNodesForQuery: 'No entity nodes match this query.',
        noAlias: 'No aliases',
        editNode: 'Edit Node',
        entityDescriptionPlaceholder: 'Entity description',
        aliasesEachLine: 'Aliases, one per line',
        saveNode: 'Save Node',
        targetEntityId: 'Target entity id',
        mergeIntoTarget: 'Merge Into Target',
        episodicCount: (count: number) => `${count} episodic`,
        rangeNodes: (start: number, end: number, total: number) => `${start}-${end} / ${total} nodes`,
        edgesTitle: 'Untyped Weighted Edges',
        addEdge: 'Add Edge',
        saveEdge: 'Save Edge',
        emptyEdges: 'No entity edges yet.',
        emptyEdgesForQuery: 'No entity edges match this query.',
        weight: 'Weight',
        coOccurrences: 'Co-occurrences',
        editEdge: 'Edit Edge',
        coOccurrenceCount: 'Co-occurrence Count',
        rangeEdges: (start: number, end: number, total: number) => `${start}-${end} / ${total} edges`,
      },
      table: {
        label: 'Memory Table',
        page: (page: number, pages: number) => `Page ${page} / ${pages}`,
        search: 'Search',
        searchPlaceholder: 'Search summary, retrieval text, or detail',
        layer: 'Layer',
        allLayers: 'All Layers',
        results: (count: number, total: number) => `Current results ${count} / total ${total}`,
        searchTerm: (query: string) => ` · Search: ${query}`,
        layerFilter: (layer: string) => ` · Layer: ${layer}`,
        addEpisodic: 'Add Episodic Memory',
        summaryLabel: 'summary (used for embedding)',
        summaryPlaceholder: 'WJJ currently likes StarCraft II most.',
        detailLabel: 'detail (returned to the long-term memory tool)',
        detailPlaceholder: 'More complete episodic details',
        importance: 'Importance',
        entityLinks: 'Entity links (entityId:weight, one per line, max 5)',
        observedStart: 'Observed Start',
        observedEnd: 'Observed End',
        createEpisodic: 'Add Episodic Memory',
        loading: 'Loading memories...',
        emptyTitle: 'No manageable memories yet',
        emptyCopy: 'Chat for a few turns so the system can write memory, or clear the search to view all results.',
        summaryColumn: 'Summary / Retrieval Text',
        time: 'Time',
        session: 'Session',
        actions: 'Actions',
        expand: 'Click to expand details',
        collapse: 'Click to collapse details',
        noBoundEntities: 'No bound entities',
        saveEpisodic: 'Save Episodic Memory',
        retrievalTextLabel: 'retrieval_text (used for embedding)',
        saveMemory: 'Save Memory',
        createdAt: 'Created At',
        notEmbedded: 'Embedding not written',
        observedTime: 'Observed Time',
        showing: (start: number, end: number, total: number) => `Showing ${start} - ${end} / ${total}`,
      },
      promptLab: {
        semanticHelper: 'Prompt that only extracts retrieval_query. It should analyze “what”, not mix in time.',
        semanticPlaceholder: 'Clear and save to fall back to the system default semantic analyzer prompt.',
        timeHelper: 'Prompt that only extracts time_range for pre-chat memory retrieval. It should analyze “when”, not the retrieval topic.',
        timePlaceholder: 'Clear and save to fall back to the system default time analyzer prompt.',
        contextHelper: 'Used by the daemon when converting old context into short-term memories. Controls how to extract at most N short-term memories from a message block.',
        contextPlaceholder: 'Clear and save to fall back to the system default context -> short-term prompt.',
        mentionHelper: 'Used before long-term memory tool recall. Extracts entity mentions only from the current question; must not create entities, merge entities, or add aliases.',
        mentionPlaceholder: 'Clear and save to fall back to the system default entity mention prompt.',
        episodicHelper: 'Stage A for background STM consolidation. Extracts entities and episodic memories; alias and merge do not happen here.',
        episodicPlaceholder: 'Clear and save to fall back to the system default episodic extraction prompt.',
        resolutionHelper: 'Stage B for background STM consolidation. Handles merge/create_new and may add alias_to_add only on merge.',
        resolutionPlaceholder: 'Clear and save to fall back to the system default entity resolution prompt.',
        shortTermHelper: 'Wrapper injected into the main prompt when short-term memories hit. The No-hit Fragments setting above controls whether misses are shown.',
        shortTermPlaceholder: 'Clear and save to fall back to the system default short-term fragment prompt.',
        fixedHelper: 'Wrapper injected into the main prompt when fixed memories hit. The No-hit Fragments setting above controls whether misses are shown.',
        fixedPlaceholder: 'Clear and save to fall back to the system default fixed fragment prompt.',
      },
    }
  }

  return {
    common: {
      none: '无',
      unknownTime: '时间未知',
      loading: '加载中…',
      previous: '上一页',
      next: '下一页',
      delete: '删除',
      save: '保存',
      enabled: '启用',
      disabled: '关闭',
    },
    errors: {
      load: '加载 sqlite 记忆失败',
      delete: '删除 sqlite 记忆失败',
      clear: '清空 sqlite 记忆失败',
      updateLayer: '更新记忆层失败',
      edit: '保存记忆编辑失败',
      contextFlush: '整理旧上下文失败',
      sleep: '执行睡眠沉淀失败',
      settings: '保存记忆配置失败',
    },
    confirms: {
      deleteSqlite: '要删除这条 sqlite 记忆吗？',
      clearAll: '要清空当前 persona 的全部 sqlite 记忆吗？这会删除短期记忆、旧长期层和固化记忆，但不会清除聊天上下文、情景记忆或其他 persona 的记忆。',
      deleteEpisodic: '要删除这条情景记忆吗？实体节点和实体边会保留。',
      deleteEntity: '要删除这个实体节点吗？相关 alias、边和情景记忆绑定会删除，但情景记忆文本会保留。',
      mergeEntity: '要把当前实体合并进目标实体吗？source 会被删除，alias / 情景绑定 / 边会迁移。',
      deleteEdge: '要删除这条实体边吗？',
    },
    notices: {
      deletedSqlite: '已删除这条 sqlite 记忆。',
      cleared: (count: number) => `已清空当前 persona 的 ${count} 条 sqlite 记忆。`,
      layerUpdated: (layer: string) => `已将记忆调整为${layer}。`,
      savedSqlite: '已保存 STM / 固化记忆，并重新写入 embedding。',
      savedEpisodic: '已保存情景记忆，并按 summary 重新写入 embedding。',
      createdEpisodic: '已新增情景记忆。',
      deletedEpisodic: '已删除这条情景记忆。',
      createdEntity: '已新增实体节点。',
      savedEntity: '已保存实体节点，并重新写入实体 embedding。',
      deletedEntity: '已删除实体节点。',
      mergedEntity: '已合并实体节点。',
      savedEdge: '已保存实体边。',
      deletedEdge: '已删除实体边。',
      contextFlushStart: '正在把旧上下文整理成短期记忆…',
      contextFlushSkipped: (reason: string) => `旧上下文暂时没有可整理的内容：${reason}。`,
      contextFlushDone: (created: number, flushed: number) => `已从活跃上下文整理出 ${created} 条短期记忆，移出 ${flushed} 条消息。`,
      sleepStart: '正在执行睡眠沉淀，把短期记忆整理进情景记忆…',
      sleepSkipped: (reason: string) => `当前无需执行睡眠沉淀：${reason}。`,
      sleepDone: (episodic: number, entities: number, deleted: number) => `睡眠完成：沉淀出 ${episodic} 条情景记忆，新增 ${entities} 个实体，消费 ${deleted} 条短期记忆。`,
      settingsSaved: '记忆检索参数、模型和 Prompt Lab 已保存。',
    },
    hero: {
      eyebrow: '记忆管理',
      title: 'sqlite Memory Console',
      copy: '这页优先把前置检索、语义分析和上下文沉淀参数摆到首屏，底部再放 Prompt Lab。大屏上会把记忆表拉宽，让检索控制和实际 memory rows 同时更好读。',
      count: (total: number) => `共 ${total} 条`,
    },
    actions: {
      refresh: '刷新',
      flush: '整理上下文',
      flushing: '正在整理旧上下文…',
      sleep: '立即睡觉',
      sleeping: '正在睡觉…',
      saveSettings: '保存配置',
      clearing: '正在清空…',
      clearAll: '清空全部记忆',
    },
    settings: {
      preRetrieval: '前置检索',
      shortTermPill: '短期记忆',
      shortTermCopy: '调整短期记忆在进入主 prompt 前的载入条数和匹配阈值。',
      fixedPill: '固化记忆',
      fixedCopy: '固化记忆可以比短期记忆更保守或更宽松，避免稳定事实和近期印象互相打架。',
      semanticLabel: '语义分析',
      semanticPill: '补全 · 深搜默认值',
      semanticCopy: '这里控制 semantic analyser 看多少历史，以及情景记忆 tool 未显式传参时的默认载入条数。',
      noHitOn: '显示“未命中”提示',
      noHitOff: '未命中时保持安静',
      rhythm: '运行节奏',
      contextPill: '缓存 · 卸载 · 短期整理',
      contextCopy: '`context` 只存在于当前模型上下文里，不参与检索。这里控制活跃上下文窗口、空闲多久后整理为短期记忆，以及单次最多生成几条短期记忆。',
      activeSession: '活跃会话',
      activeContextMessages: '活跃上下文消息数',
      totalSessionMessages: '会话消息总数',
      activeStartMessage: '活跃起点消息',
      pendingFlushUntil: '待整理终点消息',
      lastUserMessage: '最近一次用户消息',
      lastContextFlush: '最近一次上下文整理',
      sleepPill: '短期沉淀 · 情景记忆',
      sleepCopy: '固定每天一次“睡觉”，把短期记忆沉淀成情景记忆和实体图。第一版先使用固定本地时间和固定间隔天数，后续再做更复杂的睡眠规则。',
      sleepEnabled: 'Sleep Enabled',
      sleepTime: 'Sleep Time',
      sleepIntervalDays: 'Sleep Interval Days',
      lastSleep: '最近一次睡眠',
      modelLabel: '模型设置',
      modelPill: '前置检索 · 深搜工具 · 沉淀整理',
      modelCopy: '记忆相关的模型设置统一收在这里。留空会继承虚拟人的主模型；embedding provider 显式展示，embedding 模型则回退到系统默认值。',
      memoryModelPlaceholder: '例如 qwen/qwen-2.5-7b-instruct',
      embeddingModelPlaceholder: '例如 qwen/qwen3-embedding-8b',
    },
    graph: {
      label: '实体图',
      nodesUnit: '节点',
      edgesUnit: '边',
      copy: '实体节点、alias 和无类型权重边都由后台 merge/consolidation 维护。这里单独查询和分页，不再一次性渲染整张图。',
      searchLabel: '查询节点和边',
      searchPlaceholder: '按实体名、alias 或边两端搜索',
      searchState: (query: string) => query ? `图谱搜索：${query}` : '显示最近节点和最高权重边',
      addEntity: '新增实体节点',
      name: '名称',
      namePlaceholder: '例如 星际争霸2',
      type: '类型',
      confidence: '置信度',
      aliases: 'alias（逗号或换行分隔）',
      aliasesPlaceholder: '星际2\nSC2',
      description: '描述',
      descriptionPlaceholder: '这个节点在个人记忆图中的含义',
      createEntity: '新增实体',
      nodesTitle: '实体节点',
      page: (page: number, pages: number) => `第 ${page} / ${pages} 页`,
      emptyNodes: '还没有实体节点。',
      emptyNodesForQuery: '当前查询没有实体节点。',
      noAlias: '无 alias',
      editNode: '编辑节点',
      entityDescriptionPlaceholder: '实体描述',
      aliasesEachLine: 'alias，每行一个',
      saveNode: '保存节点',
      targetEntityId: '目标 entity id',
      mergeIntoTarget: '合并到目标',
      episodicCount: (count: number) => `${count} 情景`,
      rangeNodes: (start: number, end: number, total: number) => `${start}-${end} / ${total} 节点`,
      edgesTitle: '无类型权重边',
      addEdge: '新增边',
      saveEdge: '保存边',
      emptyEdges: '还没有实体边。',
      emptyEdgesForQuery: '当前查询没有实体边。',
      weight: '权重',
      coOccurrences: '共现',
      editEdge: '编辑边',
      coOccurrenceCount: '共现次数',
      rangeEdges: (start: number, end: number, total: number) => `${start}-${end} / ${total} 边`,
    },
    table: {
      label: '记忆表',
      page: (page: number, pages: number) => `第 ${page} / ${pages} 页`,
      search: '搜索',
      searchPlaceholder: '按摘要、检索文本或 detail 搜索',
      layer: '层级',
      allLayers: '全部层级',
      results: (count: number, total: number) => `当前结果 ${count} / 总数 ${total}`,
      searchTerm: (query: string) => ` · 搜索词：${query}`,
      layerFilter: (layer: string) => ` · 层级：${layer}`,
      addEpisodic: '新增情景记忆',
      summaryLabel: 'summary（用于 embedding）',
      summaryPlaceholder: 'WJJ 现在最喜欢的游戏是星际2。',
      detailLabel: 'detail（返回给长期记忆 tool 阅读）',
      detailPlaceholder: '更完整的情景细节',
      importance: '重要性',
      entityLinks: '实体绑定（entityId:weight，每行一个，最多 5 个）',
      observedStart: '观测开始',
      observedEnd: '观测结束',
      createEpisodic: '新增情景记忆',
      loading: '正在加载记忆…',
      emptyTitle: '还没有可管理的记忆',
      emptyCopy: '先去聊天几轮让系统写入 memory，或者清空搜索词查看全部结果。',
      summaryColumn: '摘要 / 检索文本',
      time: '时间',
      session: '会话',
      actions: '操作',
      expand: '点击展开详情',
      collapse: '点击收起详情',
      noBoundEntities: '无绑定实体',
      saveEpisodic: '保存情景记忆',
      retrievalTextLabel: 'retrieval_text（用于 embedding）',
      saveMemory: '保存记忆',
      createdAt: '生成时间',
      notEmbedded: '未写入 embedding',
      observedTime: '观测时间',
      showing: (start: number, end: number, total: number) => `显示 ${start} - ${end} / ${total}`,
    },
    promptLab: {
      semanticHelper: '只负责提炼 retrieval_query 的 prompt。这里应该只分析“是什么”，不要混入时间。',
      semanticPlaceholder: '清空后保存会回退系统默认的 semantic analyzer prompt。',
      timeHelper: '只负责提取记忆检索用的 time_range。这里应该只分析“什么时候”，不要混入检索主题。',
      timePlaceholder: '清空后保存会回退系统默认的 time analyzer prompt。',
      contextHelper: 'daemon 从旧上下文整理短期记忆时使用。这里控制如何从一大段消息里提炼最多 N 条短期记忆。',
      contextPlaceholder: '清空后保存会回退系统默认的 context → short-term prompt。',
      mentionHelper: '长期记忆 tool 召回前使用，只从当前问题提取实体 mention；不得创建实体、合并实体或新增 alias。',
      mentionPlaceholder: '清空后保存会回退系统默认的 entity mention prompt。',
      episodicHelper: '后台整合 STM 的阶段 A，负责抽取实体和情景记忆；alias 和 merge 不在这一阶段发生。',
      episodicPlaceholder: '清空后保存会回退系统默认的 episodic extraction prompt。',
      resolutionHelper: '后台整合 STM 的阶段 B，负责 merge/create_new，并且只允许在 merge 时通过 alias_to_add 建立 alias。',
      resolutionPlaceholder: '清空后保存会回退系统默认的 entity resolution prompt。',
      shortTermHelper: '短期记忆命中时注入主 prompt 的包装文案。是否显示未命中提示由上面的 No-hit Fragments 开关决定。',
      shortTermPlaceholder: '清空后保存会回退系统默认的 short-term fragment prompt。',
      fixedHelper: '固化记忆命中时注入主 prompt 的包装文案。是否显示未命中提示由上面的 No-hit Fragments 开关决定。',
      fixedPlaceholder: '清空后保存会回退系统默认的 fixed fragment prompt。',
    },
  }
}
