import assert from 'node:assert/strict'
import test from 'node:test'
import { mkdtempSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { agentRepo, bootstrapAppDatabases, resetDb, resetMemoryDb } from '@mas/db'
import type { LLMRequest, LLMResponse } from '@mas/core'
import {
  buildDefaultPromptTestInputs,
  getPromptTestSamples,
  runPromptTest,
  updatePromptTestSamples,
} from './handler'

function bootstrap(dbPath: string, memoryDbPath: string) {
  process.env.MAS_MEMORY_DB_PATH = memoryDbPath
  resetDb()
  resetMemoryDb()
  bootstrapAppDatabases({ dbPath, memoryDbPath })
}

function requestMessageText(request: LLMRequest | undefined) {
  const content = request?.messages[0]?.content
  if (typeof content === 'string') {
    return content
  }
  return content
    ?.filter((block) => block.type === 'text')
    .map((block) => block.text)
    .join('\n') ?? ''
}

test('prompt test samples are persisted in the agent modules without changing prompts', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'mas-prompt-tests-route-'))
  const dbPath = join(dir, 'data.db')
  const memoryDbPath = join(dir, 'memory.db')

  try {
    bootstrap(dbPath, memoryDbPath)
    const agent = agentRepo.createAgent({
      name: 'Prompty',
      model: 'claude-sonnet-4-6',
      modules: {
        memory: {
          scheme: 'sqlite',
          semanticAnalyzerPrompt: '真实语义 prompt',
        },
      },
    })!

    const saved = updatePromptTestSamples(agent.id, {
      testId: 'memory.semanticAnalyzer',
      input: {
        recentMessages: [
          { role: 'user', text: '我喜欢星际2。' },
          { role: 'assistant', text: '我记住了。' },
        ],
        currentUserMessage: '那个游戏叫什么？',
      },
    })
    assert.equal(saved.status, 200)
    const savedPayload = await saved.json()
    assert.equal(savedPayload.samples['memory.semanticAnalyzer'].currentUserMessage, '那个游戏叫什么？')

    const loaded = getPromptTestSamples(agent.id)
    assert.equal(loaded.status, 200)
    const loadedPayload = await loaded.json()
    assert.equal(loadedPayload.samples['memory.semanticAnalyzer'].currentUserMessage, '那个游戏叫什么？')
    assert.equal(loadedPayload.defaults['memory.semanticAnalyzer'].currentUserMessage, '那个游戏叫什么来着？')

    const updated = agentRepo.getAgent(agent.id)!
    assert.equal((updated.modules?.memory as { semanticAnalyzerPrompt?: string }).semanticAnalyzerPrompt, '真实语义 prompt')
    assert.equal(
      ((updated.modules?.promptTests as { samples?: Record<string, unknown> }).samples?.['memory.semanticAnalyzer'] as { currentUserMessage?: string }).currentUserMessage,
      '那个游戏叫什么？',
    )
  } finally {
    resetDb()
    resetMemoryDb()
    rmSync(dir, { recursive: true, force: true })
  }
})

test('default prompt test inputs are generated by the backend and accepted by every registered test', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'mas-prompt-tests-route-'))
  const dbPath = join(dir, 'data.db')
  const memoryDbPath = join(dir, 'memory.db')
  let activeTestId = ''
  const seenInputs = new Map<string, string>()

  const llmOutputs: Record<string, string> = {
    'memory.semanticAnalyzer': '{"retrieval_query":"星际2叫什么名字"}',
    'memory.contextToShortTerm': '{"memories":[{"display_summary":"原文说明用户喜欢星际2，Stage A 应保留 surface“星际2”。","retrieval_text":"用户说星际2是自己喜欢的游戏。","importance":0.7}]}',
    'memory.entityMention': '{"mentions":[{"surface":"星际2","type":"object","context_hint":"用户提到的游戏简称","confidence":0.91}]}',
    'memory.episodicExtraction': '{"entities":[{"local_entity_id":"local-game-1","surface":"星际2","type":"object","context_hint":"用户提到的游戏简称"}],"episodic_memories":[{"summary":"用户最喜欢的游戏是星际2。","source_quote":"我最喜欢的游戏是星际2。","importance":0.82,"entity_links":[{"local_entity_id":"local-game-1","weight":0.9}]}]}',
    'memory.entityResolution': '{"resolutions":[{"local_entity_id":"local-game-1","action":"merge","entity_id":"entity-sc2","confidence":0.9,"alias_to_add":"星际2"}]}',
    'emotion.analysis': '{"mood_delta":-0.03,"energy_delta":-0.02,"stress_delta":0.08,"trigger":"用户反馈测试压力"}',
    'relationship.analysis': '{"trust_delta":0.02,"affinity_delta":0.01,"familiarity_delta":0.03,"respect_delta":0.02,"trigger":"用户直接反馈问题"}',
    'relationshipNamed.analysis': '{"trust_delta":0.02,"affinity_delta":0.01,"familiarity_delta":0.03,"respect_delta":0.02,"trigger":"WJJ 直接反馈问题"}',
  }

  try {
    bootstrap(dbPath, memoryDbPath)
    const agent = agentRepo.createAgent({
      name: 'Prompty',
      model: 'agent-model',
      modules: {
        memory: {
          scheme: 'sqlite',
          summarizeModel: 'memory-model',
        },
        relationship: {
          scheme: 'named-multi-dim',
        },
      },
    })!

    const defaults = buildDefaultPromptTestInputs(agent)
    assert.ok(Object.keys(defaults).length >= 15)

    for (const [testId, input] of Object.entries(defaults)) {
      activeTestId = testId
      const response = await runPromptTest(agent.id, { testId, input }, {
        sendMessage: async (request) => {
          seenInputs.set(activeTestId, requestMessageText(request))
          return {
            content: [{ type: 'text', text: llmOutputs[activeTestId] ?? '{"ok":true}' }],
            stopReason: 'end_turn',
            usage: { inputTokens: 12, outputTokens: 6 },
          } satisfies LLMResponse
        },
      })

      assert.equal(response.status, 200, testId)
      const payload = await response.json()
      assert.equal(payload.testId, testId)
      if (testId in llmOutputs) {
        assert.equal(typeof payload.inputText, 'string', testId)
        assert.notEqual(payload.inputText.trim(), '', testId)
      } else {
        assert.equal(typeof payload.renderedOutput, 'string', testId)
        assert.notEqual(payload.renderedOutput.trim(), '', testId)
      }
    }

    assert.match(seenInputs.get('memory.semanticAnalyzer') ?? '', /我最喜欢的游戏是星际2/)
    assert.match(seenInputs.get('memory.semanticAnalyzer') ?? '', /那个游戏叫什么来着/)
    assert.match(seenInputs.get('memory.contextToShortTerm') ?? '', /待整理的旧上下文/)
    assert.match(seenInputs.get('memory.episodicExtraction') ?? '', /待沉淀的短期记忆/)
  } finally {
    resetDb()
    resetMemoryDb()
    rmSync(dir, { recursive: true, force: true })
  }
})

test('prompt test render mode returns the actual fragment without calling a provider', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'mas-prompt-tests-route-'))
  const dbPath = join(dir, 'data.db')
  const memoryDbPath = join(dir, 'memory.db')

  try {
    bootstrap(dbPath, memoryDbPath)
    const agent = agentRepo.createAgent({
      name: 'Prompty',
      model: 'claude-sonnet-4-6',
      modules: {
        emotion: {
          scheme: 'dimensional',
        },
      },
    })!

    const response = await runPromptTest(agent.id, {
      testId: 'emotion.fragment',
      prompt: '让情绪轻微影响语气，但不要播报数值。',
      input: {
        state: { mood: -0.25, energy: 0.4, stress: 0.7 },
      },
    }, {
      sendMessage: async () => {
        throw new Error('provider should not be called for render tests')
      },
    })

    assert.equal(response.status, 200)
    const payload = await response.json()
    assert.equal(payload.mode, 'render')
    assert.match(payload.renderedOutput, /当前情绪状态参考/)
    assert.match(payload.renderedOutput, /mood/)
    assert.match(payload.renderedOutput, /让情绪轻微影响语气/)
  } finally {
    resetDb()
    resetMemoryDb()
    rmSync(dir, { recursive: true, force: true })
  }
})

test('prompt test llm mode sends the sample input and parses entity mention output', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'mas-prompt-tests-route-'))
  const dbPath = join(dir, 'data.db')
  const memoryDbPath = join(dir, 'memory.db')
  const requests: LLMRequest[] = []

  try {
    bootstrap(dbPath, memoryDbPath)
    const agent = agentRepo.createAgent({
      name: 'Prompty',
      model: 'agent-model',
      modules: {
        memory: {
          scheme: 'sqlite',
          summarizeModel: 'memory-model',
        },
      },
    })!

    const response = await runPromptTest(agent.id, {
      testId: 'memory.entityMention',
      prompt: '自定义实体 mention prompt',
      input: {
        currentUserMessage: '星际2和魔兽世界哪个更像我以前喜欢的游戏？',
      },
    }, {
      sendMessage: async (request) => {
        requests.push(request)
        return {
          content: [{
            type: 'text',
            text: '{"mentions":[{"surface":"星际2","type":"object","context_hint":"游戏简称","confidence":0.92}]}',
          }],
          stopReason: 'end_turn',
          usage: { inputTokens: 11, outputTokens: 7 },
        } satisfies LLMResponse
      },
    })

    assert.equal(response.status, 200)
    const payload = await response.json()
    assert.equal(payload.mode, 'llm')
    assert.equal(payload.systemPrompt, '自定义实体 mention prompt')
    assert.equal(payload.model, 'memory-model')
    assert.equal(payload.usage.inputTokens, 11)
    assert.equal(payload.parsedOutput.mentions[0].surface, '星际2')
    assert.equal(requests.length, 1)
    assert.equal(requests[0]?.systemPrompt, '自定义实体 mention prompt')
    assert.match(JSON.stringify(requests[0]?.messages), /星际2和魔兽世界/)
  } finally {
    resetDb()
    resetMemoryDb()
    rmSync(dir, { recursive: true, force: true })
  }
})

test('prompt test semantic analyzer keeps prior user message when building the real analyzer input', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'mas-prompt-tests-route-'))
  const dbPath = join(dir, 'data.db')
  const memoryDbPath = join(dir, 'memory.db')
  const requests: LLMRequest[] = []

  try {
    bootstrap(dbPath, memoryDbPath)
    const agent = agentRepo.createAgent({
      name: 'Prompty',
      model: 'agent-model',
      modules: {
        memory: {
          scheme: 'sqlite',
          summarizeModel: 'memory-model',
        },
      },
    })!

    const response = await runPromptTest(agent.id, {
      testId: 'memory.semanticAnalyzer',
      input: {
        recentMessages: [
          { role: 'user', text: '我最喜欢的游戏是星际2。' },
          { role: 'assistant', text: '我记住了。' },
        ],
        currentUserMessage: '那个游戏叫什么来着？',
      },
    }, {
      sendMessage: async (request) => {
        requests.push(request)
        return {
          content: [{ type: 'text', text: '{"retrieval_query":"我最喜欢的游戏叫什么"}' }],
          stopReason: 'end_turn',
          usage: { inputTokens: 12, outputTokens: 6 },
        } satisfies LLMResponse
      },
    })

    assert.equal(response.status, 200)
    const payload = await response.json()
    assert.equal(payload.parsedOutput.retrieval_query, '我最喜欢的游戏叫什么')
    const inputText = requestMessageText(requests[0])
    assert.match(inputText, /我最喜欢的游戏是星际2/)
    assert.match(inputText, /那个游戏叫什么来着/)
  } finally {
    resetDb()
    resetMemoryDb()
    rmSync(dir, { recursive: true, force: true })
  }
})

test('prompt test llm mode returns a JSON error when the provider fails', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'mas-prompt-tests-route-'))
  const dbPath = join(dir, 'data.db')
  const memoryDbPath = join(dir, 'memory.db')

  try {
    bootstrap(dbPath, memoryDbPath)
    const agent = agentRepo.createAgent({
      name: 'Prompty',
      model: 'agent-model',
      modules: {
        memory: {
          scheme: 'sqlite',
          summarizeModel: 'memory-model',
        },
      },
    })!

    const response = await runPromptTest(agent.id, {
      testId: 'memory.contextToShortTerm',
      input: {
        messages: [
          { role: 'user', text: '我最近又开始玩星际2了。' },
          { role: 'assistant', text: '你之前也提到过它。' },
          { role: 'user', text: '对，我想让你记住它是我喜欢的游戏。' },
        ],
      },
    }, {
      sendMessage: async () => {
        throw new Error('Provider returned error')
      },
    })

    assert.equal(response.status, 502)
    const payload = await response.json()
    assert.equal(payload.error, 'Provider returned error')
    assert.equal(payload.testId, 'memory.contextToShortTerm')
    assert.equal(payload.mode, 'llm')
  } finally {
    resetDb()
    resetMemoryDb()
    rmSync(dir, { recursive: true, force: true })
  }
})
